class GestionProductos {
    iniciar(){
        productos = [
            {"id": 1,
            "nombre": "Café Italiano",
            "descripcion": "Café tipo italiano, robusto, intenso, 100% granos arábigos...",
            "precio": 2400,
            "stock": 1,
            "img": "cafe-italiano.png",
            "promo": 1,
            },
            {"id": 2,
            "nombre": "Café Brasil",
            "descripcion": "Café tipo brasil, robusto, intenso, 100% granos arábigos...",
            "precio": 2400,
            "stock": 1,
            "img": "cafe-italiano.png",
            "promo": 0,
            },
            {"id": 3,
            "nombre": "Café Colombia",
            "descripcion": "Café tipo colombia, robusto, intenso, 100% granos arábigos...",
            "precio": 2400,
            "stock": 1,
            "img": "cafe-colombia.png",
            "promo": 0,
            },
            {"id": 4,
            "nombre": "Cafetera Filtro",
            "descripcion": "Cafetera de filtro con capacidad para 0,6L.",
            "precio": 6400,
            "stock": 1,
            "img": "cafetera-filtro.png",
            "promo": 0,
            },
            {"id": 5,
            "nombre": "Cafetera Italiana",
            "descripcion": "Cafetera tipo italiana, capacidad 6 expressos",
            "precio": 9400,
            "stock": 1,
            "img": "cafetera-italiana.png",
            "promo": 0,
            },
            {"id": 6,
            "nombre": "Jarro Pitcher",
            "descripcion": "Jarro pitcher profesional, para hacer el mejor latte art!",
            "precio": 8400,
            "stock": 1,
            "img": "jarro-pitcher.png",
            "promo": 0,
            },
            
        ]
        let productosPromo =  productos.filter(prod => prod.promo === 1);//Filtra productos en promoción (promo = 1)
        //Falta el recurso para cargarlo, ya que no hay barra buscadora todavia. 
    }
}